export const SAUCES = [
  {
    id: 'buffalo',
    name: 'Hi! Buffalo',
    shortName: 'Buffalo',
    tagline: 'Butter Me Up & Watch Me Burn.',
    description: 'Classic tangy buffalo heat for wings, pizza, and everything in between. The go-to crowd pleaser — bold, familiar, and seriously addictive.',
    heat: 3,
    heatLabel: 'Hot',
    thc: '15mg',
    format: '5.2 fl oz',
    glb: '/assets/bottles/buffalo.glb',
    sachetGlb: '/assets/sachets/buffalo.glb',
    splash: '/assets/splashes/buffalo.png',
    accent: '#E8341C',
    accentSoft: 'rgba(232,52,28,0.15)',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, rgba(232,52,28,0.30) 0%, rgba(140,20,5,0.12) 45%, transparent 75%)',
    pairings: [
      { emoji: '🍗', label: 'Wings' },
      { emoji: '🍕', label: 'Pizza' },
      { emoji: '🌮', label: 'Tacos' },
      { emoji: '🥪', label: 'Subs' },
    ],
    tags: ['Vegan', 'Gluten Free', 'Lab Tested', 'Small Batch'],
    wholesale: 4.50,
    retail: 7.50,
    sachetWholesale: 0.75,
    sachetRetail: 1.50,
    facts: [
      { label: 'THC', value: '15mg' },
      { label: 'Servings', value: '10' },
      { label: 'Origin', value: 'USA' },
      { label: 'Format', value: '5.2oz' },
    ],
  },
  {
    id: 'burn',
    name: 'Hi! Burn',
    shortName: 'Burn',
    tagline: 'Not For The Faint of Heart.',
    description: 'Ghost pepper-level fire for those who want the full experience. Intense heat, complex flavor. A conversation starter guaranteed.',
    heat: 5,
    heatLabel: 'Extreme',
    thc: '15mg',
    format: '5.2 fl oz',
    glb: '/assets/bottles/burn.glb',
    sachetGlb: '/assets/sachets/burn.glb',
    splash: '/assets/splashes/burn.png',
    accent: '#FF3300',
    accentSoft: 'rgba(255,51,0,0.15)',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, rgba(255,51,0,0.32) 0%, rgba(120,10,0,0.15) 45%, transparent 75%)',
    pairings: [
      { emoji: '🌮', label: 'Tacos' },
      { emoji: '🍳', label: 'Eggs' },
      { emoji: '🍔', label: 'Burgers' },
      { emoji: '🍜', label: 'Ramen' },
    ],
    tags: ['Vegan', 'Gluten Free', 'Lab Tested', 'Ghost Pepper'],
    wholesale: 4.50,
    retail: 7.50,
    sachetWholesale: 0.75,
    sachetRetail: 1.50,
    facts: [
      { label: 'THC', value: '15mg' },
      { label: 'Servings', value: '10' },
      { label: 'Origin', value: 'USA' },
      { label: 'Format', value: '5.2oz' },
    ],
  },
  {
    id: 'bbq',
    name: 'Hi! BBQ',
    shortName: 'BBQ',
    tagline: 'Sweet Heat. Good Vibes.',
    description: 'Smoky, sweet BBQ with a slow-building warmth. Perfect for ribs, chicken, or anything off the grill. The flavor-forward choice.',
    heat: 2,
    heatLabel: 'Medium',
    thc: '15mg',
    format: '5.2 fl oz',
    glb: '/assets/bottles/bbq.glb',
    sachetGlb: '/assets/sachets/bbq.glb',
    splash: '/assets/splashes/bbq.png',
    accent: '#C97A10',
    accentSoft: 'rgba(201,122,16,0.15)',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, rgba(201,122,16,0.28) 0%, rgba(120,70,0,0.12) 45%, transparent 75%)',
    pairings: [
      { emoji: '🥩', label: 'Ribs' },
      { emoji: '🍗', label: 'Chicken' },
      { emoji: '🌽', label: 'Corn' },
      { emoji: '🍔', label: 'Burgers' },
    ],
    tags: ['Vegan', 'Gluten Free', 'Lab Tested', 'Smoky'],
    wholesale: 4.50,
    retail: 7.50,
    sachetWholesale: 0.75,
    sachetRetail: 1.50,
    facts: [
      { label: 'THC', value: '15mg' },
      { label: 'Servings', value: '10' },
      { label: 'Origin', value: 'USA' },
      { label: 'Format', value: '5.2oz' },
    ],
  },
]

export const DISPLAY_PRESETS = [
  { id: 'starter', name: 'Starter Pack', desc: '1 Display — 18 Bottles + 60 Sachets', bottles: 18, sachets: 60, multiplier: 1 },
  { id: 'double',  name: 'Double Down',  desc: '2 Displays — 36 Bottles + 120 Sachets', bottles: 36, sachets: 120, multiplier: 2 },
]